on: [ push, pull_request,workflow_dispatch ]
name: build
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...
        if: runner.os != 'Linux'

      - name: Test with coverage
        run: make test
        if: runner.os == 'Linux'

      - name: Upload coverage data to codecov.io
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
        if: runner.os == 'Linux'

      - name: Update goreportcard
        uses: creekorful/goreportcard-action@v1.0
        if: runner.os == 'Linux'
